**Chapter 2 : The Standard Library**

**Problem 1.** Write a function that accepts a list *L* and returns the minimum, maximum, and average of the entries of *L* (in that order). Can you implement this function in a single line?


Yes, I can implement this function in a single line

In [16]:
def list(L) : return min(L), max(L), sum(L)/len(L) 

**Problem 2.**  
Determine which of Python's object types are mutable and which are immutable by repeating the following experiment for an <span style="color:blue">int</span>, <span style="color:blue">str</span>, <span style="color:blue">list</span>, <span style="color:blue">tuple</span>, and <span style="color:blue">set</span>.


1. Create an object of the given type and assign a name to it.

In [17]:
integer = 1
string = "one"
list = [1,2,3]
tuple = (1,2,3)
set = {1,2,3}

2. Assign a new name to the first name. 

In [18]:
my_int = integer
my_str= string
my_list = list
my_tuple = tuple
my_set = set

3. Alter the object via only one of the names (for tuples, use my_tuple += (1,)).

In [19]:
my_int += 1
my_str += "plus"
my_list += [1,]
my_tuple += (1,)
my_set.add(4)

4. Check to see if the two names are equal. If they are, then since changing one name changed the other, the names refer to the same object and the object type is mutable. Otherwise, the names refer to different objects-meaning a copy was made in step 2-and therefore the object type is immutable. Print a statement of your conclusions that clearly indicates which object types are mutable and which are immutable. 

In [20]:
print(my_int == integer)
print(my_str == string)
print(my_list == list)
print(my_tuple == tuple)
print(my_set == set)

print("Integer, string and tuple are immutable while list and set are mutable")

False
False
True
False
True
Integer, string and tuple are immutable while list and set are mutable


**Problem 3.**  
Create a module called calculator.py. Write a function that returns the sume of two arguments and a function that returns the product of two arguments. Also use import to add the sqrt() function from the math module to the namespace. When this file is either run or imported, nothing should be executed.

In your solution file, import your new custom module. Write a function that accepts two numbers representing the lengths of th sides of a right triangle. Using only the functions from calculator.py, calculate and return the length of the hypotenuse of the triangle.

In [21]:
import calculator

def hypotenuse(a,b):
    return calculator.sqrt(calculator.sum(calculator.product(a,a),calculator.product(b,b)))

print(hypotenuse(3,4))

5.0


**Chapter 4 : Introduction to NumPy"**

**Problem 1.** There are two main ways to perform matrix multiplication in NumPy: with NumPy's dot() function(np.dot(A, B)), or with the @ operator (A @ B). Write a function that defines the following matrices as NumPy arrays.

$$
A = \begin{bmatrix}
3 & -1 & 4 \\
1 & 5 & -9
\end{bmatrix}
\quad
B = \begin{bmatrix}
2 & 6 & -5 & 3 \\
5 & -8 & 9 & 7 \\
9 & -3 & -2 & -3
\end{bmatrix}
$$

Return the matirx product AB.
  For examples of array initialization and matrix multiplication, use objcet introspection in IPython to look up the documentation for np.ndarray, np.array() and np.dot().


In [22]:
import numpy as np


def matrix_A():
    A = np.array([[3, -1,  4],
                  [1,  5, -9]])
    return A

def matrix_B():
    B = np.array([[2,  6, -5,  3],
                  [5, -8,  9,  7],
                  [9, -3, -2, -3]])
    
    return B
 
A = matrix_A()
B = matrix_B()

multiply_dot = np.dot(A,B)

print("matrix product AB using np.dot():\n", multiply_dot)

multiply_at = A@B

print("matrix product AB using @:\n", multiply_at)

matrix product AB using np.dot():
 [[ 37  14 -32 -10]
 [-54  -7  58  65]]
matrix product AB using @:
 [[ 37  14 -32 -10]
 [-54  -7  58  65]]


**Problem 2.** Write a function that defines the following matrix as a NumPy array. 
$$
A = \begin{bmatrix}
3 & -1 & 4 \\
1 & 5 & -9
\end{bmatrix}
$$

Return the matirx $-A^3$ + $9A^2$ $-15A$.
 In this context, $A^2$ = $AA$ (the matrix product, not the component-wise square).  The somewhat surprising result is a demonstration of the Cayley-Hamilton theorem.

In [23]:
import numpy as np

def matrix_A():
    A = np.array([[3, 1, 4],
                  [1, 5, 9],
                  [-5, 3, 1]])
    return A

def CHtheorem(A):
    # Cayley–Hamilton form (example coefficients for illustration)
    return -A @ A @ A + 9 * (A @ A) - 15 * A

A = matrix_A()
print("Cayley-Hamilton theorem:\n", CHtheorem(A))


Cayley-Hamilton theorem:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


**Problem 5.** Write a function that defines the following matrices as NumPy arrays. 
$$
A = \begin{bmatrix}
0 & 2 & 4 \\
1 & 3 & 5
\end{bmatrix}
\quad
B = \begin{bmatrix}
3 & 0 & 0 \\
3 & 3 & 0 \\
3 & 3 & 3
\end{bmatrix}
\quad
C = \begin{bmatrix}
-2 & 0 & 0 \\
0 & -2 & 0 \\
0 & 0 & -2
\end{bmatrix}
$$

Use Numpy's stacking functions to create and return the block matrix:
$$
\begin{bmatrix}
0 & A^T & I \\
A & 0 & 0 \\
B & 0 & C
\end{bmatrix}
$$ ,
where $I$ is the 3 x 3 identity matrix and each $0$ is a matrix of all zeros of appropriate size. A block matrix of this form is used in the Interior Point method for linear optimization

In [24]:
import numpy as np


def matrix_A():
    A = np.array([[0, 2,  4],
                  [1,  3, 5]])
    return A

def matrix_B():
    base = np.ones((3, 3))   
    B = np.tril(base * 3)    
    return B

def matrix_C():
    C = -2 * np.eye(3)   
    return C

def matrix_I(A):
    I = np.eye(A.shape[1])
    return I

A = matrix_A()
B = matrix_B()
C = matrix_C()
I = matrix_I(A)

def block_matrix():
    top = np.hstack([np.zeros((A.shape[1],A.shape[1])), A.T, I])
    middle = np.hstack([A, np.zeros((A.shape[0], A.shape[0])), np.zeros((A.shape[0], A.shape[1]))])
    bottom = np.hstack([B, np.zeros((B.shape[0], A.shape[0])), C])

    Block = np.vstack([top,middle,bottom])
    return Block

print("Block matrix:\n", block_matrix())

Block matrix:
 [[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0.  0. -0. -0. -2.]]


**Chapter 3 : Object-Oriented Programming"**

**Problem 1.** Expand the $Backpack$ class to match the following specifications.

1. Modify the constructor so that it accepts three total arguments: **name**, **color**, and **max_size** (in that order). Make **max_size** a keyword argument that defaults to 5. Stre each input as an attribute.  

In [ ]:
class Backpack:
    def __init__(self,name,color,max_size=5):
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []

2. Modify the **put()** method to check that the backpack does not go over capacity. If there are already **max_size** items or more, print "No Room!" and do not add the item to the contents list.

In [26]:
class Backpact:
    def put(self, item):
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else :
            self.contents.append(item)

3. Write a new method called **dump()** that resets the contents of the backpack to an empty list. This method should not receive any arguments (except self).

In [27]:
class Backpack:
    def dump(self):
        self.contents = []

4. Documentation is especially important in classes so that the user knows what an object's attributes represent and how to use methods appropriately. Update (or write) the docstrings for the __init__(), put(), and dump() methods, as well as the actual class docstring (under class but before __init__()) to reflect the changes form parts **1-3** of this problem.

In [ ]:
class Backpack:
    """
    A Backpack object that stores items up to a maximum capacity.

    Attributes:
        name (str): The name of the backpack.
        color (str): The color of the backpack.
        max_size (int): Maximum number of items allowed in the backpack (default = 5).
        contents (list): The list of items currently in the backpack.

    Methods:

        __init__(self, name, color, max_size=5) :
          Initializes a new Backpack with a name, color, and optional max_size.

          Arguments:
            name (str): The name of the backpack.
            color (str): The color of the backpack.
            max_size (int, optional): Maximum capacity of the backpack. Defaults to 5.

          Operations:
          
            - Calls the Backpack constructor to set up name, color, and max_size.
               
            
        put(self, item) :
          adds an item to the backpack if there is room.

          Arguments:
            item (str): The item to be added.

          Operations:
            - If the backpack is already at or above capacity (max_size),
              prints "No Room!" and does not add the item.
            - Otherwise, appends the item to contents.
    
            
        dump(self) :
          empty the backpack by resetting its contents to an empty list.

          Arguments:
            None (only self is required)

          Operations:
            - Clears all items in contents.
     
"""

    def __init__(self, name, color, max_size=5):
    
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []

    def put(self, item):
    
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)

    def dump(self):
         self.contents = []


To ensure that your class works properly, write a test function outside outside of the **Backapck** class that instantiates and analyzes a **Backpack** object.

In [ ]:
def test_backpack():
    testpack = Backpack("Barry", "black")
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    for item in ["pencil","pen","paper","computer"]:
        testpack.put(item)
        print("Contents:",testpack.contents)


test_backpack()


"""
It works well
"""

Contents: ['pencil']
Contents: ['pencil', 'pen']
Contents: ['pencil', 'pen', 'paper']
Contents: ['pencil', 'pen', 'paper', 'computer']


'\n\nIt works well\n\n'

**Problem 2.** Write a **Jetpack** class that inherits from the **Backpack** class.

1. Override the constructor so that in addtion to a name, color, and maximum size, it also accpets an amount of fuel. Change the default value of max_size to 2, and set the default value of fuel to 10. Store the fuel as an attribute. 

In [29]:
class Jetpack(Backpack) : 
    def __init__(self, name ,color, max_size=2,fuel =10) :
        Backpack.__init__(self,name,color,max_size)
        self.fuel = fuel
        self.closed = True

2. Add a **fly()** method that accepts an amount of fuel to be burned and decrements the fuel attribute by that amount. If the user tries to burn more fuel than remains, print "Not enough fuel!" and do not decrement the fuel.

In [32]:
class Jetpack(Backpack) : 
    def fly(self, fuel_burned) :
        if self.fuel < fuel_burned:
            print("Not enough fuel!")
        else: 
            self.fuel -= fuel_burned

3. Override the **dump()** method so that both the contents and the fuel tank are emptied.

In [33]:
class Jetpack(Backpack) : 
    def dump(self) :
        self.contents = []
        self.fuel = 0

4. Write clear, detailed docstrings for the class and each of its methods.

In [42]:
class Jetpack(Backpack):
    """
    A Jetpack is a subclass of Backpack that carries fuel, which is not from Backpack.
    It inherits all functionality from the Backpack class but adds operations for fuel, which is "fly" function.

    Attributes:
        name (str): The name of the Jetpack (inherited from Backpack).
        color (str): The color of the Jetpack (inherited from Backpack).
        max_size (int): Maximum number of items allowed in the Jetpack (default = 2, which is smaller than Backpack).
        contents (list): A list of items currently in the Jetpack (inherited from Backpack).
        fuel (int): The current amount of fuel stored in the Jetpack (default = 10).

    Methods:

        __init__(self, name, color, max_size=2) :
          Initializes a new Jetpack with a name, color, and optional max_size.

          Arguments:
            name (str): The name of the Jetpack (inherited from Backpack).
            color (str): The color of the Jetpack (inherited from Backpack).
            max_size (int): Maximum number of items allowed in the Jetpack (default = 2, which is smaller than Backpack).
            fuel (int): The current amount of fuel stored in the Jetpack (default = 10).
          
          Operations:
            - Calls the Backpack constructor to set up name, color, and max_size.
            - Initializes the fuel attribute with the given value. 
           
        fly(self, fuel-burned) :
          Consume fuel which remains.

         Arguments:
            fuel_burned (int): The amount of fuel to use 

         Operations:
            - If there is not enough fuel (fuel < fuel_burned),
              prints "Not enough fuel!" and does not reduce fuel.
            - Otherwise, decreases the fuel by fuel_burned.
            
                 
        dump(self) :
          empty the Jetpack by resetting its contents to an empty list and set fuel zero.

         Arguments:
            None (only self is required)

         Operations:
            - Clears all items in contents.
            - Set fuel to 0.     
     

    """

    def __init__(self, name ,color, max_size=2,fuel =10) :
        Backpack.__init__(self,name,color,max_size)
        self.fuel = fuel
        self.closed = True

    def fly(self, fuel_burned):
       
        if self.fuel < fuel_burned:
            print("Not enough fuel!")
        else:
            self.fuel -= fuel_burned
        
    def dump(self):
        self.contents = []
        self.fuel = 0
